### PR TITLE
Bugfix - `dontfail` was set to a truthy value by default also closes #16

### LINKED ISSUE #16: Words with single quotes before or after are being marked misspelled
Here is a few examples,
```spellcheck  Running spell checker for /templates/development-helpers/ misspell  The word ''Name' is misspelled```
`misspell  The word ''data' is misspelled`
`misspell  The word ''none'' is misspelled`

I can work on this. Any guesses on where to start looking?

Could it be related to this?
https://github.com/minivan/middleman-spellcheck/blame/e3a85d910fd99d92e9d17480ce72154118050af7/lib/middleman-spellcheck/spellchecker.rb#L80

### PR DESCRIPTION
**Pull request by mwils**
added Spellcheck exit status
modified output messages for clarity

### CODE REVIEW

**Comment by minivan** [comment]
Thanks a lot! Can you please merge in the current master and then push again? I will publish a new gem version immediately after it.

Thanks agian

**Comment by mwils** [comment]
Sure, just a minute

**Comment by mwils** [comment]
Hold on I will make it a rebase

**Comment by mwils** [comment]
Let me know if you would rather have a rebase.

**Comment by mwils** [comment]
Any word on getting this merged? Let me know if there are failing test or something I missed. Ember guides is using this as a spellchecker.

**Comment by minivan** [comment]
:+1: Bumping up the version!

**Pull request merged**
